---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$(whoami)/hairways
    - source /home/$(whoami)/virtualenv/hairways/3.7/bin/activate
    - cd $DEPLOYPATH
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py collectstatic --no-input
